### ISSUE TITLE
Windows is skipped

### ISSUE THREAD

**Issue by gonzalocasas** [conda-forge/planarity-feedstock#9]
This recipe skips Windows (without a clear reason as to why that is). I sent a PR to add [python-planarity](https://github.com/conda-forge/staged-recipes/pull/7582) to conda-forge since that one comes from `pip` and has planarity vendorized in it, but the reviewers -rightly so- requested to use `planarity` recipe instead of vendorizing it.  In order to do that, I would really need Windows support on this feedstock.

If I spend time adding it and sending a PR, would it be considered for merge?

**Comment by isuruf** [comment]
> If I spend time adding it and sending a PR, would it be considered for merge?

Absolutely. Windows is skipped just because I didn't have time to add support.

**Comment by gonzalocasas** [comment]
great! i'll give it a go then!

**Comment by isuruf** [comment]
@gonzalocasas, have a look at https://github.com/conda-forge/planarity-feedstock/pull/10. It currently fails with, `..\c\planarityCommandLine.c(9) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory`

That file needs to be patched to not include `unistd.h` on windows. If you can fix it and send a PR, I'll be happy to review

**Comment by isuruf** [comment]
Fixed with https://github.com/conda-forge/planarity-feedstock/pull/11
